spring:
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: localhost:9092 #${KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
server:
  port: 8082

topics: data-temperature,data-power,data-voltage #${KAFKA_SUBSCRIBED_TOPICS} #here will be stored a list of topics that we will subscribe on and process