version: '3.0'

networks:
  app:
    driver: bridge

services:
  store:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app
    env_file:
      - .env
    ports:
      - '8083:8083'
