version: '3.0'

networks:
  app:
    driver: bridge

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
  kafka-data:
    driver: local
  zookeeper-data:
    driver: local

services:

  analyser:
    #    image: 'jambbo/data-analyser-microservice:latest'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app
    depends_on:
      - db
      - zookeeper
      - kafka
    env_file:
      - .env
    ports:
      - '8082:8082'

  db:
    image: postgres:15.1-alpine
    networks:
      - app
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5439:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    networks:
      - app
    ports:
      - "2182:2181"

  kafka:
    image: wurstmeister/kafka:latest
    networks:
      - app
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  redis:
    image: redis:7.2-rc-alpine
    networks:
      - app
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data






